From ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt install -y \
    clang-tools clang lld lldb llvm-dev libclang-dev \
    wget curl ca-certificates zip unzip wine \
    cmake ninja-build

ENV DEBIAN_FRONTEND=dialog
ENV WORKDIR=root/project
RUN mkdir $WORKDIR

#Set the working dir to the env variable
WORKDIR $WORKDIR


COPY scripts scripts

SHELL ["/bin/bash", "-c"]
RUN mkdir packages \
    && cd packages \
    && ./../scripts/download_win_sysroot.sh

COPY test test
COPY fuzz fuzz
COPY CMakeLists.txt CMakeLists.txt

COPY src src
COPY cmake_config cmake_config

RUN cmake -GNinja -S . -B winBuild  \
    -DCMAKE_BUILD_TYPE=Release \
    -DBuildTest=TRUE \
    -DCMAKE_TOOLCHAIN_FILE=cmake_config/llvm-win-cross.cmake

RUN ninja -C./winBuild

# To get wine to run 32 and 64 bit binaries you have to do the install in stages
#RUN dpkg --add-architecture i386
#RUN apt-get update \
#    && apt install -y \
#    wine32

ENV WINEPATH="/root/project/packages/win_sysroot/crt/lib/x64"
ENV WINEPATH="$WINEPATH;/root/project/packages/win_sysroot/sdk/lib/um/x64"
ENV WINEPATH="$WINEPATH;/root/project/packages/win_sysroot/sdk/lib/ucrt/x64"
RUN wine cmd /C winBuild/src/cli/Warf.exe -e "5*(2+3-1)" --show_tree
RUN wine cmd /C winBuild/test/WarfLang_TEST.exe




