name: clang-format Check
on:
  pull_request:
    branches:
      - '**'
    paths:
      - '**.cpp'
      - '**.h'
      - .github/workflows/clang-format.yml
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'src'
          - 'fuzz'
          - 'test'
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check for C/C++ programs.
      uses: jidicula/clang-format-action@v4.8.0
      with:
        clang-format-version: '14'
        check-path: ${{ matrix.path }}