name: CMake osxcross Cross-Compile

on:
  push:
    branches:
      - master
      - feature/macOS-cross
    paths:
      - '**.cpp'
      - '**.h'
      - '**CMakeLists.txt'
      - .github/workflows/cmake-osxcross.yml
  pull_request:
    branches:
      - '**'
    paths:
      - '**.cpp'
      - '**.h'
      - '**CMakeLists.txt'
      - .github/workflows/cmake-osxcross.yml
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v2
    - name: install Darling dependencies
      run: |
        sudo apt install wget unzip  \
        cmake ninja-build ca-certificates \
        libavcodec58 libavformat58 libavutil56 \
        libcairo2 libdbus-1-3 libegl1 libgif7 libgl1 \
        libglu1-mesa libglu1 libpulse0 libswresample3 \
        libxcursor1 libxkbfile1 libxrandr2 libfuse2
    
    - name: Create Packages Environment
      working-directory: ${{github.workspace}}
      run: |
        mkdir packages

    - name: Download Darling
      working-directory: ${{github.workspace}}/packages
      run: |
        wget https://github.com/darlinghq/darling/releases/download/v0.1.20220704/darling_0.1.20220704.focal_amd64.deb
    
    - name: Install Darling
      working-directory: ${{github.workspace}}/packages
      run: |
        sudo dpkg -i darling_0.1.20220704.focal_amd64.deb
    
    - name: Test Darling
      working-directory: ${{github.workspace}}/packages
      run: |
        wget https://github.com/farzonl/warfLang/releases/download/Warf-0.0.7/Warf-Darwin-x86_64.zip
        unzip Warf-Darwin-x86_64.zip
        darling shell artifacts/Warf -e "a = 4*(5+1)/2" --show_tree

    - name: Set variables
      run: |
        APP=$(cat $GITHUB_WORKSPACE/src/lib/Version/appName.txt)
        VER=$(cat $GITHUB_WORKSPACE/src/lib/Version/version.txt)
        echo "VERSION=$VER" >> $GITHUB_ENV
        echo "APPNAME=$APP" >> $GITHUB_ENV
    
    