name: License Check

on:
  push:
    branches:
      - master
    paths:
      - '**.cpp'
      - '**.h'
      - .github/workflows/license-check.yml
  pull_request:
    branches:
      - '**'
    paths:
      - '**.cpp'
      - '**.h'
      - .github/workflows/license-check.yml
    

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v2
    -
       name: Set up Go
       uses: actions/setup-go@v3
       with:
         go-version: 1.19
    - run: go install github.com/google/addlicense@latest
    - name: Run license check
      run: ${{github.workspace}}/scripts/license-check.sh
